### ISSUE TITLE
Problem choosing anime & no subtitles

### ISSUE THREAD

**Issue by OmarAHex** [Trigus42/crunchyroll-dl#1]
There's a problem where it always chooses a certain predefined anime but it's fixable in a second in the code.

**Comment by Trigus42** [comment]
Since you closed it, I guess I just updated the script when opened this issue and it is resolved now?

**Comment by OmarAHex** [comment]
Actually I'm very new to github and was trying to delete my comment, but ended up making it worse. I didn't update anything on the github as I don't know how to but I edited my version of the file locally and it works well. Just wondering though is there any way to get subtitles? I tried using the ydl "--all-subs" option and still didn't get any subtitles in the downloaded file.

**Comment by Trigus42** [comment]
On which anime exactly? I tried it with JoJo and with the anime I accidentally hard coded into it and had no problems.

**Comment by OmarAHex** [comment]
The anime I'm downloading is The Promised Neverland, I tried multiple times and even tried downloading the subtitle file alone (added skip download) and it still downloaded the video with no sub. Tried multiple media players and enabled subs but no subtitle tracks were found. Which options are you using to download subtitles?

**Comment by Trigus42** [comment]
That is weird. I tried it and it worked:
![grafik](https://user-images.githubusercontent.com/59501676/105580323-fe1bbc80-5d8b-11eb-8bac-688ca3b8ba65.png)
![grafik](https://user-images.githubusercontent.com/59501676/105580329-007e1680-5d8c-11eb-8c74-7ec58987d579.png)

**Comment by OmarAHex** [comment]
![2021-01-23 (2)](https://user-images.githubusercontent.com/75140567/105611691-889ff400-5d6b-11eb-8672-7f40dbe18f9c.png)

here is the relevant part of the debug information (I would need dozens of pics to show all), it clearly says that it downloaded the subtitle files, and they are in fact in the destination folder during the download, but after the download finishes they are deleted, logically one would assume that they have been incorporated into the mp4, but clearly they aren't, I double checked that subtitles are on. A temporary solution that I can use for now is to copy the .ass files into a different folder and wait until the download finishes, then open the video and add it's corresponding subtitles, which seems to work, but it kind of ruins the whole point of the process being automated. I might also write a short script to copy the .ass files into a separate folder until the download finishes then add them to the mp4s with ffmpeg. I don't think this is a problem with your file, but it's weird because it has worked with YouTube videos.

**Comment by OmarAHex** [comment]
The subtitles were in fact being downloaded and added to the mp4s, you were right my bad. It's just that none of my available media players supported them, despite them having an option for subtitles, I just downloaded VLC and it's working perfectly. Thank you very much.
