### ISSUE TITLE
No module named 'youtube_dl'

### ISSUE THREAD

**Issue by proall** [Trigus42/crunchyroll-dl#8]
Some required modules were not found:
 No module named 'youtube_dl'

Please ensure all modules listed in requirements.txt are installed.

YES, I ALEADY installed Youtube-dl with the requirements.txt, i tried the install "pip3 install youtube-dl" even.
What can i do?

**Comment by Trigus42** [comment]
There isn't much that could go wrong there. You are probably using pip in another python environment than you are running the script with. This could happen, for example, if you have multiple version of python installed.

Try:
```bash
$ python3 -m pip install -r requirements.txt
$ python3 main.py
```

**Comment by proall** [comment]
NVM, FIXED, the problem was that the Python installed via Microsoft..
3.9 version.

**Comment by proall** [comment]
Really ThankYou, plz keep updating the Script!
